//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_employee()
        {
            this.tbl_plogin = new HashSet<tbl_plogin>();
        }
    
        public int EID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string eaddress { get; set; }
        public string Birthday { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public string Contactno { get; set; }
        public string Nationality { get; set; }
        public string Age { get; set; }
        public string Imagepath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_plogin> tbl_plogin { get; set; }
    }
}
