//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_patient
    {
        public int PID { get; set; }
        public string PName { get; set; }
        public string Paddress { get; set; }
        public string Disease { get; set; }
    }
}
