//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_plogin
    {
        public int LginID { get; set; }
        public string UserName { get; set; }
        public string userpasword { get; set; }
        public string role { get; set; }
        public int EID { get; set; }
    
        public virtual tbl_employee tbl_employee { get; set; }
    }
}
